# Generated by Django 4.0 on 2024-09-29 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': 'This is Blog'},
        ),
    ]
